"""
Provenance Guard — backend service for classifying submitted creative content
as likely AI-generated, likely human-written, or uncertain, with confidence
scoring, transparency labels, an appeals workflow, rate limiting, and a
structured audit log.
"""
import json
import os
import re
import sqlite3
import statistics
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, g, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

load_dotenv()

DB_PATH = os.path.join(os.path.dirname(__file__), "data", "provenance.db")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
GROQ_MODEL = "llama-3.3-70b-versatile"

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

def get_db():
    if "db" not in g:
        g.db = sqlite3.connect(DB_PATH)
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(exception=None):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_log (
            content_id TEXT PRIMARY KEY,
            creator_id TEXT,
            timestamp TEXT,
            text_preview TEXT,
            llm_score REAL,
            llm_rationale TEXT,
            stylometric_score REAL,
            confidence REAL,
            attribution TEXT,
            label TEXT,
            status TEXT,
            appeal_reasoning TEXT,
            appeal_timestamp TEXT
        )
        """
    )
    conn.commit()
    conn.close()


# ---------------------------------------------------------------------------
# Signal 1: LLM-based classification (Groq)
# ---------------------------------------------------------------------------

def get_llm_signal(text: str):
    """
    Returns (score, rationale) where score is in [0,1]:
    0 = confidently human-written, 1 = confidently AI-generated.
    Falls back to a neutral score if Groq is unavailable, so the rest of the
    pipeline remains testable without a live API key.
    """
    if not GROQ_API_KEY:
        return 0.5, "LLM signal unavailable (no GROQ_API_KEY set); neutral fallback."

    try:
        from groq import Groq

        client = Groq(api_key=GROQ_API_KEY)
        prompt = (
            "You are assessing whether a piece of writing was generated by an AI "
            "language model or written by a human. Consider stylistic tells such as "
            "generic hedging, overly balanced phrasing, formulaic transitions "
            "(e.g. 'furthermore', 'it is important to note'), versus idiosyncratic "
            "human voice, specific personal detail, and irregular phrasing.\n\n"
            "Respond ONLY with a JSON object, no other text, in this exact form:\n"
            '{"ai_score": <float 0 to 1, 1 means certainly AI-generated>, '
            '"rationale": "<one sentence>"}\n\n'
            f"Text to assess:\n\"\"\"\n{text}\n\"\"\""
        )
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            max_tokens=200,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = response.choices[0].message.content.strip()
        raw = re.sub(r"^```(json)?|```$", "", raw, flags=re.MULTILINE).strip()
        parsed = json.loads(raw)
        score = float(parsed["ai_score"])
        score = max(0.0, min(1.0, score))
        return score, parsed.get("rationale", "")
    except Exception as exc:  # noqa: BLE001
        return 0.5, f"LLM signal error, neutral fallback: {exc}"


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics (pure Python)
# ---------------------------------------------------------------------------

def get_stylometric_signal(text: str):
    """
    Returns a single 0-1 'AI-likeness' score from sentence-length variance,
    type-token ratio, and punctuation density. AI text tends to be more
    uniform (lower variance, narrower vocabulary diversity for its length,
    more conventional punctuation); human text tends to be noisier.
    """
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    words = re.findall(r"[A-Za-z']+", text)

    if len(words) < 5 or len(sentences) < 1:
        return 0.5  # not enough signal in very short text

    # 1. Sentence length variance (in words). Low variance -> more AI-like.
    sent_lengths = [len(re.findall(r"[A-Za-z']+", s)) for s in sentences]
    if len(sent_lengths) > 1:
        variance = statistics.pvariance(sent_lengths)
    else:
        variance = 0.0
    # Normalize: variance of ~0 -> AI-like (1.0), variance >= 40 -> human-like (0.0)
    variance_score = max(0.0, min(1.0, 1 - (variance / 40)))

    # 2. Type-token ratio (vocabulary diversity). Lower diversity for length -> more AI-like.
    unique_words = set(w.lower() for w in words)
    ttr = len(unique_words) / len(words)
    # Typical human casual writing TTR ~0.5-0.7+; very repetitive/uniform -> lower.
    # Map: ttr <= 0.4 -> AI-like (1.0), ttr >= 0.75 -> human-like (0.0)
    ttr_score = max(0.0, min(1.0, 1 - ((ttr - 0.4) / 0.35)))

    # 3. Punctuation density (variety of punctuation per 100 words). Low variety -> more AI-like.
    punct_chars = re.findall(r"[,;:\-\u2014\(\)\"']", text)
    punct_density = len(punct_chars) / max(1, len(words)) * 100
    # Very low punctuation variety (formulaic, mostly periods/commas only) -> AI-like
    punct_score = max(0.0, min(1.0, 1 - (punct_density / 15)))

    combined = (variance_score * 0.4) + (ttr_score * 0.4) + (punct_score * 0.2)
    return round(max(0.0, min(1.0, combined)), 3)


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------

LLM_WEIGHT = 0.65
STYLOMETRIC_WEIGHT = 0.35

AI_THRESHOLD = 0.75
HUMAN_THRESHOLD = 0.35


def combine_scores(llm_score: float, stylometric_score: float) -> float:
    combined = (LLM_WEIGHT * llm_score) + (STYLOMETRIC_WEIGHT * stylometric_score)
    return round(max(0.0, min(1.0, combined)), 3)


def attribution_from_score(score: float) -> str:
    if score >= AI_THRESHOLD:
        return "likely_ai"
    if score < HUMAN_THRESHOLD:
        return "likely_human"
    return "uncertain"


# ---------------------------------------------------------------------------
# Transparency label generation
# ---------------------------------------------------------------------------

def generate_label(score: float) -> str:
    pct = f"{round(score * 100)}%"
    attribution = attribution_from_score(score)
    if attribution == "likely_ai":
        return (
            f"This content shows strong signals of AI generation (confidence: {pct}). "
            "Our system is fairly confident this was produced by an AI tool rather "
            "than written by a human."
        )
    if attribution == "likely_human":
        return (
            f"This content shows strong signals of human authorship (confidence: {pct}). "
            "Our system found little evidence of AI generation."
        )
    return (
        f"We can't confidently determine whether this content was AI-generated or "
        f"human-written (confidence: {pct}). Treat this attribution as inconclusive."
    )


# ---------------------------------------------------------------------------
# Audit log helpers
# ---------------------------------------------------------------------------

def write_log_entry(record: dict):
    db = get_db()
    db.execute(
        """
        INSERT INTO audit_log (
            content_id, creator_id, timestamp, text_preview,
            llm_score, llm_rationale, stylometric_score, confidence,
            attribution, label, status, appeal_reasoning, appeal_timestamp
        ) VALUES (:content_id, :creator_id, :timestamp, :text_preview,
                   :llm_score, :llm_rationale, :stylometric_score, :confidence,
                   :attribution, :label, :status, :appeal_reasoning, :appeal_timestamp)
        """,
        record,
    )
    db.commit()


def get_log_entries(limit: int = 50, status: str = None):
    db = get_db()
    if status:
        rows = db.execute(
            "SELECT * FROM audit_log WHERE status = ? ORDER BY timestamp DESC LIMIT ?",
            (status, limit),
        ).fetchall()
    else:
        rows = db.execute(
            "SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(r) for r in rows]


def compute_analytics():
    """
    Aggregates the audit log into: detection-pattern breakdown by attribution
    tier, the appeal rate, and signal disagreement rate (the extra metric).
    All numbers are computed live from audit_log -- no separate storage.
    """
    db = get_db()

    total = db.execute("SELECT COUNT(*) AS c FROM audit_log").fetchone()["c"]

    if total == 0:
        return {
            "total_submissions": 0,
            "detection_patterns": {},
            "average_confidence": None,
            "appeal_rate": None,
            "appeal_count": 0,
            "signal_disagreement_rate": None,
            "signal_disagreement_count": 0,
        }

    tier_rows = db.execute(
        "SELECT attribution, COUNT(*) AS c FROM audit_log GROUP BY attribution"
    ).fetchall()
    detection_patterns = {
        row["attribution"]: {
            "count": row["c"],
            "percentage": round(row["c"] / total * 100, 1),
        }
        for row in tier_rows
    }

    avg_confidence = db.execute(
        "SELECT AVG(confidence) AS avg_c FROM audit_log"
    ).fetchone()["avg_c"]

    appeal_count = db.execute(
        "SELECT COUNT(*) AS c FROM audit_log WHERE status = 'under_review'"
    ).fetchone()["c"]

    # Signal disagreement rate: the two signals land on opposite sides of the
    # 0.5 midpoint (one leans AI, the other leans human). Computed in Python
    # since it compares two columns per row rather than a single aggregate.
    all_rows = db.execute(
        "SELECT llm_score, stylometric_score FROM audit_log"
    ).fetchall()
    disagreements = sum(
        1
        for row in all_rows
        if (row["llm_score"] >= 0.5) != (row["stylometric_score"] >= 0.5)
    )

    return {
        "total_submissions": total,
        "detection_patterns": detection_patterns,
        "average_confidence": round(avg_confidence, 3) if avg_confidence is not None else None,
        "appeal_rate": round(appeal_count / total * 100, 1),
        "appeal_count": appeal_count,
        "signal_disagreement_rate": round(disagreements / total * 100, 1),
        "signal_disagreement_count": disagreements,
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True) or {}
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "anonymous")

    if not text:
        return jsonify({"error": "field 'text' is required"}), 400

    llm_score, llm_rationale = get_llm_signal(text)
    stylometric_score = get_stylometric_signal(text)
    confidence = combine_scores(llm_score, stylometric_score)
    attribution = attribution_from_score(confidence)
    label = generate_label(confidence)

    content_id = str(uuid.uuid4())
    record = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "text_preview": text[:120],
        "llm_score": llm_score,
        "llm_rationale": llm_rationale,
        "stylometric_score": stylometric_score,
        "confidence": confidence,
        "attribution": attribution,
        "label": label,
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    write_log_entry(record)

    return jsonify(
        {
            "content_id": content_id,
            "attribution": attribution,
            "confidence": confidence,
            "label": label,
            "signals": {
                "llm_score": llm_score,
                "llm_rationale": llm_rationale,
                "stylometric_score": stylometric_score,
            },
        }
    )


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning", "").strip()

    if not content_id or not creator_reasoning:
        return jsonify({"error": "fields 'content_id' and 'creator_reasoning' are required"}), 400

    db = get_db()
    row = db.execute(
        "SELECT * FROM audit_log WHERE content_id = ?", (content_id,)
    ).fetchone()
    if row is None:
        return jsonify({"error": "content_id not found"}), 404

    db.execute(
        """
        UPDATE audit_log
        SET status = 'under_review',
            appeal_reasoning = ?,
            appeal_timestamp = ?
        WHERE content_id = ?
        """,
        (creator_reasoning, datetime.now(timezone.utc).isoformat(), content_id),
    )
    db.commit()

    return jsonify(
        {
            "content_id": content_id,
            "status": "under_review",
            "message": "Appeal received and logged. A human reviewer will examine this case.",
        }
    )


@app.route("/log", methods=["GET"])
def log():
    status = request.args.get("status")
    limit = int(request.args.get("limit", 50))
    return jsonify({"entries": get_log_entries(limit=limit, status=status)})


@app.route("/log/<content_id>", methods=["GET"])
def log_single(content_id):
    db = get_db()
    row = db.execute(
        "SELECT * FROM audit_log WHERE content_id = ?", (content_id,)
    ).fetchone()
    if row is None:
        return jsonify({"error": "content_id not found"}), 404
    return jsonify(dict(row))


@app.route("/analytics", methods=["GET"])
def analytics():
    return jsonify(compute_analytics())


@app.route("/dashboard", methods=["GET"])
def dashboard():
    data = compute_analytics()
    if data["total_submissions"] == 0:
        return "<h1>Provenance Guard Dashboard</h1><p>No submissions yet.</p>"

    tier_rows_html = ""
    for tier, stats in data["detection_patterns"].items():
        bar_width = stats["percentage"]
        tier_rows_html += f"""
        <div class="metric-row">
          <span class="metric-label">{tier}</span>
          <div class="bar-track"><div class="bar-fill" style="width:{bar_width}%"></div></div>
          <span class="metric-value">{stats['count']} ({stats['percentage']}%)</span>
        </div>
        """

    html = f"""
    <html>
    <head>
      <title>Provenance Guard — Dashboard</title>
      <style>
        body {{ font-family: -apple-system, Arial, sans-serif; max-width: 720px; margin: 40px auto; color: #1a1a1a; }}
        h1 {{ font-size: 22px; }}
        h2 {{ font-size: 16px; margin-top: 32px; color: #444; }}
        .stat-grid {{ display: flex; gap: 24px; margin: 16px 0; }}
        .stat-box {{ flex: 1; border: 1px solid #ddd; border-radius: 8px; padding: 16px; text-align: center; }}
        .stat-number {{ font-size: 28px; font-weight: 700; }}
        .stat-label {{ font-size: 12px; color: #666; margin-top: 4px; }}
        .metric-row {{ display: flex; align-items: center; gap: 10px; margin: 8px 0; }}
        .metric-label {{ width: 130px; font-size: 13px; }}
        .bar-track {{ flex: 1; background: #eee; border-radius: 4px; height: 14px; overflow: hidden; }}
        .bar-fill {{ background: #4a7cf5; height: 100%; }}
        .metric-value {{ width: 100px; font-size: 12px; color: #444; text-align: right; }}
      </style>
    </head>
    <body>
      <h1>Provenance Guard — Analytics Dashboard</h1>
      <div class="stat-grid">
        <div class="stat-box"><div class="stat-number">{data['total_submissions']}</div><div class="stat-label">Total submissions</div></div>
        <div class="stat-box"><div class="stat-number">{data['average_confidence']}</div><div class="stat-label">Avg. confidence score</div></div>
        <div class="stat-box"><div class="stat-number">{data['appeal_rate']}%</div><div class="stat-label">Appeal rate ({data['appeal_count']} appeals)</div></div>
        <div class="stat-box"><div class="stat-number">{data['signal_disagreement_rate']}%</div><div class="stat-label">Signal disagreement rate</div></div>
      </div>
      <h2>Detection patterns by tier</h2>
      {tier_rows_html}
      <p style="margin-top:32px; font-size:12px; color:#888;">Live data from /analytics, computed from the audit log.</p>
    </body>
    </html>
    """
    return html


if __name__ == "__main__":
    init_db()
    app.run(debug=True, port=5000)